name: Build DEB

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.2"

jobs:
  build_deb:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libfuse2 libmpv-dev mpv libmimalloc-dev libmimalloc2.0 libtag1-dev

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version:  ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build TagLib and copy to project
        run: |
          if [ ! -d linux/external ]; then
          mkdir -p linux/external
          fi

          cd linux/external
          git clone --depth 1 --recurse-submodules https://github.com/taglib/taglib.git
          cd taglib

          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
          make -j$(nproc)

          cp taglib/libtag.so.2 ../../../libs/x86_64/

          cd ../../../../

      - name: Enable flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build DEB
        run: PATH="$PATH:$HOME/.pub-cache/bin" flutter_distributor package --platform linux --targets deb

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: result-deb
          path: dist/*
