name: Build TAR on ARM

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.2"

jobs:
  build_tar_arm:
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libfuse2 libmpv-dev mpv libmimalloc-dev libmimalloc2.0 libtag1-dev

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build TagLib and copy to project
        run: |
          if [ ! -d linux/external ]; then
          mkdir -p linux/external
          fi

          cd linux/external
          git clone --depth 1 --recurse-submodules https://github.com/taglib/taglib.git
          cd taglib

          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
          make -j$(nproc)

          cp taglib/libtag.so.2 ../../../libs/x86_64/

          cd ../../../../

      - name: Build App
        run: |
          flutter build linux
          

      - name: Create TAR
        run: |
          cd build/linux/arm64/release/bundle
          tar --use-compress-program=zstd -cvf ../../../../../music-linux.tar.zst *
          cd ../../../../..

      - name: Upload TAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-tar
          path: music-linux.tar.zst